import Link from "next/link";
import type { Metadata } from "next";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "About — AskMM.ai",
  description:
    "Learn how AskMM.ai uses AI to search Medical Medium's YouTube content and find timestamped answers to your health questions.",
};

export default function AboutPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[var(--background)]">
      <Header />

      <main className="flex-1 overflow-y-auto">
        <article className="max-w-2xl mx-auto px-6 py-12">
          <div className="prose prose-sm max-w-none prose-headings:text-[var(--foreground)] prose-p:text-[var(--foreground)] prose-strong:text-[var(--foreground)] prose-li:text-[var(--foreground)] prose-a:text-primary-500 prose-a:no-underline hover:prose-a:underline prose-hr:border-[var(--border)]">
            <h1 className="text-3xl font-semibold tracking-tight mb-2">
              About AskMM.ai
            </h1>
            <p className="text-[var(--muted)] text-base !mt-0 mb-8">
              A search tool for Medical Medium&apos;s YouTube content.
            </p>

            <hr />

            <h2>What Is AskMM.ai?</h2>
            <p>
              AskMM.ai helps you find specific information across Medical
              Medium&apos;s YouTube content.
            </p>
            <p>
              Think of it like a librarian who has watched every single Medical
              Medium video and can instantly tell you which video and exact
              timestamp contains the answer to your question.
            </p>
            <p>
              When you search for something like &ldquo;what does AW say about
              healing vitiligo?&rdquo;, the tool searches through hundreds of
              hours of content and shows you the exact moments where he discusses
              that topic &mdash; complete with direct links and timestamps to his
              actual words.
            </p>

            <hr />

            <h2>How It Works</h2>
            <p>
              AskMM.ai uses AI to search through transcripts from Anthony
              William&apos;s YouTube channel.
            </p>
            <p>
              When you type a question, the AI understands the meaning behind it.
              For example, if you search for &ldquo;what does AW say about itchy
              red skin?&rdquo;, the AI will also find videos where Anthony
              discusses &ldquo;dermatitis&rdquo; or &ldquo;eczema&rdquo;, even if
              he doesn&apos;t use the exact phrase &ldquo;itchy red skin&rdquo;.
            </p>
            <p>
              It then shows you a summary of what Anthony William said (pulled
              from the original video transcript), along with direct links to the
              videos with specific timestamps. If a topic is discussed in multiple
              videos, you&apos;ll see several sources.
            </p>
            <p>
              You can click the timestamped link to watch the clip and hear
              Anthony William&apos;s actual words in their full context.
            </p>

            <hr />

            <h2>Where Does the Content Come From?</h2>
            <p>
              All content comes exclusively from{" "}
              <strong>
                Anthony William&apos;s official YouTube channel
              </strong>
              . The database of transcripts updates automatically every day when
              new content is posted, so you always have access to the latest
              videos.
            </p>

            <hr />

            <h2>Disclaimer</h2>
            <p>
              AskMM.ai is a search tool &mdash; not a substitute for watching
              Anthony William&apos;s original videos.
            </p>
            <p>
              Results are generated by AI from auto-transcribed YouTube content.
              This means:
            </p>
            <ul>
              <li>
                Transcriptions may contain errors from speech-to-text conversion
              </li>
              <li>
                The AI may miss important context from the broader video
              </li>
              <li>
                Summaries might not capture nuance, sarcasm, or indirect
                references
              </li>
            </ul>
            <p>
              Always verify information by clicking through to the original video
              sources. The timestamps are there so you can hear Anthony
              William&apos;s actual words in full context.
            </p>

            <hr />

            <h2>About The Creator</h2>
            <p>
              Hi, I&apos;m Beer (yes, that&apos;s my real name, though I prefer
              celery juice). I&apos;m a 22-year-old from the Netherlands.
            </p>
            <p>
              My mom introduced me to Medical Medium back in 2018 when she was
              dealing with chronic illness. I started diving deep into the
              information myself in 2023, and it changed my life.
            </p>
            <p>
              Here&apos;s the thing: Anthony William has produced SO much content
              over the years. Hundreds of livestreams, podcasts, videos&hellip;
              it&apos;s incredible, but it can also be overwhelming. I&apos;d find
              myself thinking, &ldquo;I know he talked about this somewhere, but
              which video was it in? And where in that 2-hour
              livestream?&rdquo; I recently started learning about AI and realized
              I could build something to solve this exact problem.
            </p>
            <p>
              What really moved me was when someone in the community told me this
              tool helps people with severe brain fog who can&apos;t watch full
              podcasts or streams but still want to know what Medical Medium says
              about certain topics. That&apos;s exactly the kind of impact I was
              hoping to have.
            </p>

            <hr />

            <h2>Get in Touch</h2>
            <p>
              I&apos;d love to hear from you! Whether you have suggestions, found
              an issue, or just want to share how the tool has helped you:
            </p>
            <p>
              <strong>Email:</strong>{" "}
              <a href="mailto:beerrodenburg@gmail.com">
                beerrodenburg@gmail.com
              </a>
            </p>
            <p>
              <strong>WhatsApp:</strong>{" "}
              <a
                href="https://wa.me/31615350896"
                target="_blank"
                rel="noopener noreferrer"
              >
                +31 6 15 35 08 96
              </a>
            </p>
            <p>
              Thank you for taking the time to understand how this tool works. I
              hope it helps you on your healing journey.
            </p>
            <p>&mdash; Beer</p>
          </div>

          <div className="mt-10 mb-12 text-center">
            <Link
              href="/"
              className="inline-flex items-center gap-2 px-6 py-3 bg-primary-500 text-white rounded-full hover:bg-primary-600 transition-colors text-sm font-medium"
            >
              Start searching
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M3 8H13M13 8L9 4M13 8L9 12"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </Link>
          </div>
        </article>
      </main>
    </div>
  );
}
